data['LAUNCHER_BASE_PORT'] = 17777
data['SOAP_BASE_PORT'] = 25000
data['I2O_BASE_PORT'] = 54320
data['FRL_BASE_PORT'] = 55320

dataNetwork = ".dv3rbs1v0.cms"

hosts = [
    "dvrubu-c2e34-06-01", # first RU
    "dvrubu-c2e34-08-01",
    "dvrubu-c2e34-10-01",
    "dvrubu-c2e34-12-01",
    "dvrubu-c2e34-16-01",
    "dvrubu-c2e34-18-01",
    "dvrubu-c2e34-20-01",
    "dvrubu-c2e34-27-01",

    "dvrubu-c2e34-29-01", # first BU
    "dvrubu-c2e34-31-01", 
    "dvrubu-c2e34-33-01",
    "dvrubu-c2e34-35-01",
    "dvrubu-c2e34-37-01",
    "dvrubu-c2e34-39-01",
    "dvrubu-c2e34-41-01",

    "dvrubu-c2e34-14-01",
    "dvrubu-c2e33-06-01",
    "dvrubu-c2e33-08-01",
]

# add RUs and BUs
# (we do this in a combined loop to keep the port
# numbers the same as generated by the .txt file)
for index, host in enumerate(hosts):
    data['RU%d_SOAP_HOST_NAME' % index] = host + ".cms"
    data['RU%d_I2O_HOST_NAME' % index] = host + dataNetwork

    if index >= 8 and index < 15:
        data['BU%d_SOAP_HOST_NAME' % (index-8)] = host + ".cms"
        data['BU%d_I2O_HOST_NAME' % (index-8)] = host + dataNetwork




