#!/bin/sh

for TEST_NAME in `/bin/ls -1d ${EVB_TESTER_HOME}/cases/$1/[0-9]* | sed -nre "s:${EVB_TESTER_HOME}/cases/+::p" | sort -V` ; do
  startTime=`date "+%H:%M:%S"`
  printf "%-32s: $startTime " $TEST_NAME

  testDir=${EVB_TESTER_HOME}/tmp/${TEST_NAME}
  mkdir -p ${testDir}

  logfile=${testDir}/`basename ${TEST_NAME}`.log
  if runTest $TEST_NAME 2>&1 > ${logfile}
  then
    date=`date "+%H:%M:%S"`
    echo -e "$date \033[1;30;42m Passed \033[30;47;0m"
  else
    date=`date "+%H:%M:%S"`
    echo -e "$date \033[1;30;41m FAILED \033[30;47;0m"
  fi
done
